### ISSUE TITLE
【新功能提议】通过对已完成计算的产线修改设施数量来重新量化

### ISSUE THREAD

**Issue by mei-iem** [122474363/DSQ#1]
可以按照设施数量添加和修改需求，可以在当前已有的量化中通过修改某原料的设施数量来调整全部的产量
例如：
![image](https://github.com/122474363/DSQ/assets/97957593/4c66bf2f-6b42-4633-a5e2-22e19a9197de)
这是一条60导弹组的产线，这时制作导弹组需要2.67个制作台，那么我可以将2.67更改为3来动态更新其他原料以及产物的设施数量和产量。亦或是通过更改生产磁铁的设施数量来动态更新其他的设施数量和产量

**Comment by 122474363** [comment]
好的。这个问题已经收到，我应该没有这个能力去处理这一块，只能看有没有大佬来跟进了。
目前提供一个方案可以供临时使用：可以修改输入数量来进行间接调整这里的数值。

**Comment by 122474363** [comment]
https://github.com/122474363/DSQ/pull/4
