### ISSUE TITLE
轨道采集器也是制造台的配方啊

### ISSUE THREAD

**Issue by wistfate** [122474363/DSQ#10]
![戴森球计划量产量化计算器工具 和另外 2 个页面 - 用户配置 1 - Microsoft​ Edge 2023_12_29 18_35_10](https://github.com/122474363/DSQ/assets/154920778/fb4d563b-34b9-478d-a29a-437c00ce718d)

**Comment by Akashicf** [comment]
排除满电的蓄电池即可
