### ISSUE TITLE
【修改提议】物品选择器排版和文字

### ISSUE THREAD

**Issue by PrainLopez** [122474363/DSQ#12]
# 问题1：物品选择界面部分图标放置不理想
![屏幕截图 2024-01-02 232933](https://github.com/122474363/DSQ/assets/61592725/3b6d8464-6555-4bcb-bdf7-0d3ee0c86604)
可燃冰和光子被放在了最下一行，这一行目前游戏中仍是留空的，可能以后会填入新物品。
建议将可燃冰移到 `第2行，第8列`，这是游戏中可燃冰制石墨烯配方的位置
建议将临界光子移到 `第7行，第13列`，这是游戏中绿糖制翘曲配方的位置，是离反物质最近的空位

# 问题2：物品选择器的按钮标题不正确
选择器的按钮，鼠标放上去弹出的提示里有多处错别字，如 **高级石墨**，**蓝矩阵**，**星际物流运输机**等等，它们的title属性需要修正一下

# 解决方案
我正在开发另一个网页小工具，上述问题是我在对照复刻时发现的，如果取得允许，我可以直接PR修补

**Comment by PrainLopez** [comment]
我不太了解jQuery，请问选择器的 data-name 和 title 都是直接读取的 `Script/data.json` 里的吗？
更正：刚看到 `Script/data.js` 里也使用了蓝矩阵等称呼，作者麻烦考虑一下这里的数据耦合性有多高，光改 `data.json` 和 `data.js` 不触及其他逻辑代码能不能安全解决title的问题？

**Comment by PrainLopez** [comment]
另：HTML中没有看到选择器的样式内容，能告知一下选择器网格是在哪里写的吗？

**Comment by 122474363** [comment]
感谢您的关注， 您可以随时进行PR。
问题1，这是一个不建议去修复的问题，因为物品的排列方式是与游戏内一一对应的。 而可燃冰和临界光子 属于非建造类的产物并未在游戏的建造图表内，所以我另起一行作为一个独立的储物位置。
问题2，欢迎您的修正以及细心的观察，您可以随时进行PR进行修复。但是修改这个可能可能需要同步修改蓝图内的数据，否则可能会导致计算器错误。
—————————————————————————————————————
Script/data.json 是资源文件，你可以理解为图标，这个文件主要是用来存放选择器内的图标和标记图标的位置，若是问题2则这个文件无需改动。
Script/data.js 是核心代码，你可以参照里面的一些数据进行了解。一般来说，大部分数据的关联性会和蓝图数据进行关联，也就是说你修改了Script/data.js 也很有可能会需要去修改 Script/blueprint.js 的内容，否则可能会导致程序错误（也有可能程序运行正常，但是蓝图生成错误）。

完整的项目结构可以看这里：https://github.com/122474363/DSQ?tab=readme-ov-file#%E9%A1%B9%E7%9B%AE%E7%BB%93%E6%9E%84
