### ISSUE TITLE
bug 无法生成微晶组件和处理器蓝图

### ISSUE THREAD

**Issue by fengyimoou** [122474363/DSQ#14]
![firefox_17-46-02](https://github.com/122474363/DSQ/assets/155627745/5949b599-e9ec-4f5d-82a4-c44b2622356e)

**Comment by 122474363** [comment]
可能是缓存问题？

![image](https://github.com/122474363/DSQ/assets/24683970/5275e9e3-1bfe-449c-aa65-d0276aa75a57)
