### ISSUE TITLE
bug 隐藏科技多了增产的效果（游戏中仅有加速）

### ISSUE THREAD

**Issue by angie1630** [122474363/DSQ#15]
![QQ图片20240106160758](https://github.com/122474363/DSQ/assets/142202332/bac2e75e-cc29-4411-8ad6-df49e3b22b98)
![QQ图片20240106160807](https://github.com/122474363/DSQ/assets/142202332/5cc82ee8-2a95-4ca2-bb5e-81cbfd0ef47a)
重组式制造台、负熵熔炉、自演化研究站在游戏中均只能被加速制造（而不是增产），计算器里显示可以被增产制造，请移除。

**Comment by 122474363** [comment]
已修复：https://github.com/122474363/DSQ/commit/0db2c0b15e512f2aa733a21e645abbead462448d
