### ISSUE TITLE
不能生成使用X射线裂解公式的蓝图

### ISSUE THREAD

**Issue by qysnn** [122474363/DSQ#16]
系统提示
`
包含不支持的配方: hydrogen+refinedOil->hydrogen+energeticGraphite，
请排除对应物品（目前只支持通过(位面)熔炉、制造台、精炼厂、对撞机、（量子）化工厂、研究站六类生产设施进行制造的物品）
`
但是这个配方是在精炼厂里生产的

复现方式：选红糖-切换石墨的生产配方-点生成蓝图

**Comment by 122474363** [comment]
![image](https://github.com/122474363/DSQ/assets/24683970/fdffee42-5d3b-45e2-b855-aa282ec24ad1)
这样就正常了，如果切换了瑟吉石墨的生产配方包含了氢则会出现问题（当然你可以手动排除氢），因为
![image](https://github.com/122474363/DSQ/assets/24683970/74104e76-b378-48e8-9d02-8e2e4687da39)

但是我不确定这是不是一个BUG的存在。

**Comment by qysnn** [comment]
是的，使用默认的石墨的配方是可以正常生成蓝图的，我的意思是`hydrogen+refinedOil->hydrogen+energeticGraphite`这个配方是在精炼厂里生产的但是依旧报错，所以好像跟这里的提示文字对不上？

**Comment by 122474363** [comment]
> 是的，使用默认的图纸的配方是可以正常生成蓝图的，我的意思是`hydrogen+refinedOil->hydrogen+energeticGraphite`这个配方是在精炼厂里生产的但是仍然报错，所以想跟这里的提示文字对不上？

应该不是文字错误，应该就是蓝图这块的逻辑有问题，但是我目前没有这个能力去修复，

**Comment by SheldonHoo233** [comment]
这也是我一开始用到计算器就特别希望能够修好的功能，检查后发现本身其实是由于原作者禁用了这两条公式生成蓝图导致，改好后试用才明白为何作者禁用该功能。
(公式部分解除禁用只需要修改这两行)
```
Scripts\data.js
417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
```
X射线裂解和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运出方式，无法保证产物优先满足工厂自身需求。（如X射线裂解得到的氢，可能全被其他生产设施用完了，X射线裂解的工厂就停止了。）可能需要大佬为这两种公式的原油精炼厂优先设置供货的分拣器节点(?)。

**Comment by 122474363** [comment]
> 这也是我一开始使用好的辅助功能就特别希望能够修改功能，检查后发现本身是由于原作者取消了这个配额生成蓝图导致，改好后百度才知道为何作者取消该功能。（ 公式部分解除禁止只需要修改这行）
> 
> ```
> Scripts\data.js
> 417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
> 509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
> ```
> 
> X射线和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运输方式，能够保证产物优先满足工厂自身需求。（如X射线的得到的）氢，可能全被其他生产设施用完了，X货架需要的工厂就停止了。）可能大佬为这两种公式的原油精炼厂优先设置供货的分拣器节点（？）。

主要是怕修改了有错误，你可以尝试一下 修改后本地部署 会不会有问题，

**Comment by SheldonHoo233** [comment]
评论时候不小心打漏了两个字，意思是……可能后续需要大佬研究如何为这两种公式优先提供供货分拣器节点。嗯，只是个想法，我会试着研究一下。如果有其他更了解无带流蓝图生成代码的大佬能出手修改就更好了。😆

**Comment by 122474363** [comment]
> > 这也是我一开始使用好的辅助功能就特别希望能够修改功能，检查后发现本身是由于原作者取消了这个配额生成蓝图导致，改好后百度才知道为何作者取消该功能。（ 公式部分解除禁止只需要修改这行）
> > ```
> > Scripts\data.js
> > 417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
> > 509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > X射线和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运输方式，能够保证产物优先满足工厂自身需求。（如X射线的得到的）氢，可能全被其他生产设施用完了，X货架需要的工厂就停止了。）可能大佬为这两种公式的原油精炼厂优先设置供货的分拣器节点（？）。
> 
> 主要是怕修改了有错误，你可以尝试一下 修改后本地部署 会不会有问题，

主要蓝图也不是我做的 我也不是大佬。。。

**Comment by SheldonHoo233** [comment]
> > 这也是我一开始使用好的辅助功能就特别希望能够修改功能，检查后发现本身是由于原作者取消了这个配额生成蓝图导致，改好后百度才知道为何作者取消该功能。（ 公式部分解除禁止只需要修改这行）
> > ```
> > Scripts\data.js
> > 417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
> > 509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > X射线和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运输方式，能够保证产物优先满足工厂自身需求。（如X射线的得到的）氢，可能全被其他生产设施用完了，X货架需要的工厂就停止了。）可能大佬为这两种公式的原油精炼厂优先设置供货的分拣器节点（？）。
> 
> 主要是怕修改了有错误，你可以尝试一下 修改后本地部署 会不会有问题，

我意思是……可能后续需要大佬研究如何为这两种公式优先提供供货分拣器节点。嗯，只是个想法，我会试着研究一下修改。如果有其他更了解无带流蓝图生成代码的大佬能出手修改就更好了。😆

**Comment by 122474363** [comment]
> > > 这也是我一开始使用好的辅助功能就特别希望能够修改功能，检查后发现本身是由于原作者取消了这个增益生成蓝图导致，改好后百度才为何作者取消该功能。（公式部分解除禁止结尾要修改这行）
> > > ```
> > > Scripts\data.js
> > > 417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
> > > 509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > X射线和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运输方式，能够保证产物优先满足工厂自身需求。（如X射线的得到的）氢，可能全被其他生产设施用完了，X个货架需要的工厂就停了。）可能大佬为这两种公式的原油精炼厂优先设置供应的分拣器节点（？）。
> > 
> > 
> > 主要是怕修改了有错误，你可以尝试一下修改后本地部署会不会有问题，
> 
> 我的意思是……可能后续需要大佬研究如何为这两种公式优先提供供货分拣器节点。嗯，只是个想法，我会尝试研究一下修改一下。如果有其他更了解无带流蓝图生成代码修改的大佬能出手就更好了。😆

好的， 因为之前的蓝图大佬弃游了，所以 我对这一块的逻辑也是一窍不通。。只能看有没有大佬去修改了。至于为什么不做氢这一块 我觉得应该是有什么顾虑。

**Comment by 122474363** [comment]
> > > > 这也是我一开始使用好的辅助功能就特别希望能够修改功能，检查后发现本身是由于原作者取消了这个增益生成蓝图导致，改好后百度才为何作者取消该功能。（公式部分解除禁止结尾要修改这行）
> > > > ```
> > > > Scripts\data.js
> > > > 417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
> > > > 509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > X射线和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运输方式，能够保证产物优先满足工厂自身需求。（如X射线的得到的）氢，可能全被其他生产设施用完了，X个仓库需要的工厂就停了。）可能大佬为这两种公式的原油精炼厂优先设置供应的分排序器节点（？）。
> > > 
> > > 
> > > 主要是怕修改了有错误，你可以尝试一下修改一下以后本地部署会不会有问题，
> > 
> > 
> > 我的意思是……可能后续需要大佬研究如何为这四种公式优先提供供货分拣器节点。嗯，只是个想法，我会尝试研究一下修改一下。如果有其他更了解无带流蓝图生成代码修改的大佬能出手就更好了。😆
> 
> 好了，因为之前的蓝图​​大佬抛弃了，所以我对这块的逻辑也是一窍不通。。只能看有没有大佬去修改了。至于为什么不做氢这块我觉得应该是有什么顾虑。

![image](https://github.com/122474363/DSQ/assets/24683970/107a66df-35fe-491c-af57-691315bccf88)

**Comment by SheldonHoo233** [comment]
> > > > > 这也是我一开始使用好的辅助功能就特别希望能够修改功能，检查后发现本身是由于原作者取消了这个增益生成蓝图导致，改好后百度才为何作者取消该功能。（公式部分解除禁止结尾要修改这行）
> > > > > ```
> > > > > Scripts\data.js
> > > > > 417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
> > > > > 509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > X射线和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运输方式，能够保证产物优先满足工厂自身需求。（如X射线的得到的）氢，可能全被其他生产设施用完了，X个仓库需要的工厂就停了。）可能大佬为这两种公式的原油精炼厂优先设置供应的分排序器节点（？）。
> > > > 
> > > > 
> > > > 主要是怕修改了有错误，你可以尝试一下修改一下以后本地部署会不会有问题，
> > > 
> > > 
> > > 我的意思是……可能后续需要大佬研究如何为这四种公式优先提供供货分拣器节点。嗯，只是个想法，我会尝试研究一下修改一下。如果有其他更了解无带流蓝图生成代码修改的大佬能出手就更好了。😆
> > 
> > 
> > 好了，因为之前的蓝图​​大佬抛弃了，所以我对这块的逻辑也是一窍不通。。只能看有没有大佬去修改了。至于为什么不做氢这块我觉得应该是有什么顾虑。
> 
> ![image](https://private-user-images.githubusercontent.com/24683970/295195816-107a66df-35fe-491c-af57-691315bccf88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDA5NzIsIm5iZiI6MTcwNDgwMDY3MiwicGF0aCI6Ii8yNDY4Mzk3MC8yOTUxOTU4MTYtMTA3YTY2ZGYtMzVmZS00OTFjLWFmNTctNjkxMzE1YmNjZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDExNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NjMxMDU4MzQ4M2VlZGY1MzNjYmE3Njc4NmRhYzU5MWM5ZWNkNDRhZjU3YWE2NmYzNjVhZTNjOTA4M2U3MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CjqtFLo1CxNF1eEyf8Zl42JfAPhW2yK_CYm3W1a2kXw)

似乎在之前版本已经有某位大佬修复了同时作为原料和产物时，蓝图没有该物品的bug。现在硬把蓝图运作起来，特别是同时用X裂解和重整精炼一起生产红糖，别提它们抢的原材料有多欢了。嗯，确实也不算重要的公式，极度缺煤和想用掉多余的氢气的时候可能才用得到。

**Comment by 122474363** [comment]
> > > > > > 这也是我一开始使用好的辅助功能就特别希望能够修改功能，检查后发现本身是由于原作者取消了这个增益生成蓝图导致，改好后百度才为何作者取消该功能。（公式部分解除禁止结尾要修改这行）
> > > > > > ```
> > > > > > Scripts\data.js
> > > > > > 417 "refinedOil+hydrogen+coal=refinedOil": 121, // 精炼油
> > > > > > 509 "hydrogen+refinedOil=hydrogen+energeticGraphite": 58, // 氢 高能石墨
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > X射线和重整精炼，分别为2氢->3氢和2精炼油->3精炼油，蓝图目前的产物运输方式，能够保证产物优先满足工厂自身需求。（如X射线的得到的）氢，可能全被其他生产设施用完了，X个仓库需要的工厂就停了。）可能大佬为这两种公式的原油精炼厂优先设置供应的分排序器节点（？）。
> > > > > 
> > > > > 
> > > > > 主要是怕修改了有错误，你可以尝试一下修改一下以后本地部署会不会有问题，
> > > > 
> > > > 
> > > > 我的意思是……可能后续需要大佬研究如何为这四种公式优先提供供货分拣器节点。嗯，只是个想法，我会尝试研究一下修改一下。如果有其他更了解无带流蓝图生成代码修改的大佬能出手就更好了。😆
> > > 
> > > 
> > > 好了，因为之前的蓝图​​大佬抛弃了，所以我对这块的逻辑也是一窍不通。。只能看有没有大佬去修改了。至于为什么不做氢这块我觉得应该是有什么顾虑。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/24683970/295195816-107a66df-35fe-491c-af57-691315bccf88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDA5NzIsIm5iZiI6MTcwNDgwMDY3MiwicGF0aCI6Ii8yNDY4Mzk3MC8yOTUxOTU4MTYtMTA3YTY2ZGYtMzVmZS00OTFjLWFmNTctNjkxMzE1YmNjZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDExNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NjMxMDU4MzQ4M2VlZGY1MzNjYmE3Njc4NmRhYzU5MWM5ZWNkNDRhZjU3YWE2NmYzNjVhZTNjOTA4M2U3MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CjqtFLo1CxNF1eEyf8Zl42JfAPhW2yK_CYm3W1a2kXw)
> 
> 似乎在之前版本已经有某位大佬修复了同时作为原料和产物时，蓝图没有该物品的bug。现在硬把蓝图运作起来，特别是同时用X裂解和重整精炼一起生产红糖，别提它们抢的原材料有多欢了。嗯，确实也不算重要的公式，极度缺煤和想用掉多余的氢气的时候可能才用得到。

所以现在只能将就用， 除非有个大佬来接管蓝图这一块的逻辑。
