### ISSUE TITLE
全蓝色但是显示碰撞并且爪子错位

### ISSUE THREAD

**Issue by wistfate** [122474363/DSQ#18]
![Dyson Sphere Program 2024_1_13 5_05_55](https://github.com/122474363/DSQ/assets/154920778/c987a6ba-3e16-4471-9c9c-60d880bc5256)

**Comment by SheldonHoo233** [comment]
距离太近可能只是电塔生成的太近，生产不一定有问题。我的建议是拍下来试试看，实在不行的话建议缩小规模多次建造。
