### ISSUE TITLE
BUG: 信号塔增产剂效果

### ISSUE THREAD

**Issue by scegg** [122474363/DSQ#20]
实际上信号塔只允许使用加速效果。

**Comment by 122474363** [comment]
请提供游戏中的图片

**Comment by scegg** [comment]
<img width="364" alt="image" src="https://github.com/122474363/DSQ/assets/3340557/1b63ceb8-7fda-45a9-883b-53a9c7ff43c7">
Production speedup右侧开关不可点击。
