### ISSUE TITLE
自演化研究站无法配置加速配方

### ISSUE THREAD

**Issue by wanghaowms** [122474363/DSQ#22]
使用蓝图生成功能生成60min/s的红色矩阵，使用三级加速配方，使用矩阵研究站可以配置加速，使用黑雾矩阵就仍然是增产配方

**Comment by 122474363** [comment]
没看懂你的意思

**Comment by wanghaowms** [comment]
60蓝糖，生成图纸，增产剂使用加速。选择使用自演化研究站，催化剂配方是额外产出，选择使用矩阵研究站就是正常的加速

BLUEPRINT:0,10,6001,0,0,0,0,0,638418678049670000,0.9.26.13026,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%2Fmin,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%20%2Fmin"H4sIAAAAAAAAA42TPU7DQBCFx8aO8U9sh8TQRkIU1KFEYkzuwD0QBZR0XMNnQByADgooECUNNzFeza5nzA4iI43yZPl7M/viDWBagW3SPcCrlQEc8luI1L811VX+EvS2yqoqAVJrMXp3uNncWOhZ6KdL01/JKdTWrM+JuT4ig9BBPLUT+mFr2hiYiobOejJ4jMhgzxm8vxWjAeupQTZ0ag2amAwiu1kLcH/h67Ot6Y/kGFwGIlKIGQD0NcNmioEDAc8YQPQ1w7ECJ2JV9DXDMwXeZ6BDXzOceHA4JA9wDvQV/Hv2NL2D6cdDldFPLZKud049Z8BNq9XUM+XsBQOIvmY4V+C5WBV9zXChwCUDHfqa4bmSehNT6tUuZ/8rdXsL1yJpqanMBgtl/QUDbprUDPt/WTjcd1r/gB58IyVuJktN9ZmcwFLJ4Nbe1aV9rxVgq5mslGOsODQH1CrcKHDD53bAWoV7DmGEfwALP8cbnQUAAA=="4BC8787D6B008C2C2603117B9D9250F0


BLUEPRINT:0,10,6001,0,0,0,0,0,638418676621490000,0.9.26.13026,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%2Fmin,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%20%2Fmin"H4sIAAAAAAAAC42TMU7DQBBFZ00cx7FjmxAnbSREQR1KpIyJxA04CKKAko5r+AyIA1BSQIEoabiJ2WXWnrV3kDzSKF/Wvj+z37GCfinbpBuANysVbPgUIvVQU90k19DYyvI8A4j106DzVn1w2H0ToyWTgI7VuNvdWejV0S9Xpr+jczi2hk1Cg2836k8ctRBPrR39dDBtDEyFuucNGTxPyGDSGny8p50B675Boju2BmVIBqHdrAJ43Pv64mD6MzrtwuTsAKYMAPqaYTPFwMqBIwYQfc3wVIBnzqroa4YjAY4ZqNHXDM88ONDJA1xqNR9z9zh+GPwLqRL6KZyki9Gppwy00wox9US4+4IBRF8znApw5qyKvmZ4IcA5AzX6muFMSL0MKfVizN3/S91+hVsnaVdTmQ2WwvpLBtpprmbYf2WB/t5p/RN68IOUuJnsaqqv6AxWQgb39mNf2XOVA1aSSSlco+TQWqAQ4bUAr/neLbAV4YZD6OBfpsdJm+YFAAA="53EE0214BB3E51FC00B6B86BF77F90A6

**Comment by 122474363** [comment]
有图片吗

**Comment by wanghaowms** [comment]
&nbsp;
 

 

 
&nbsp;
 
BLUEPRINT:0,10,6001,0,0,0,0,0,638418678049670000,0.9.26.13026,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%2Fmin,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%20%2Fmin"H4sIAAAAAAAAA42TPU7DQBCFx8aO8U9sh8TQRkIU1KFEYkzuwD0QBZR0XMNnQByADgooECUNNzFeza5nzA4iI43yZPl7M/viDWBagW3SPcCrlQEc8luI1L811VX+EvS2yqoqAVJrMXp3uNncWOhZ6KdL01/JKdTWrM+JuT4ig9BBPLUT+mFr2hiYiobOejJ4jMhgzxm8vxWjAeupQTZ0ag2amAwiu1kLcH/h67Ot6Y/kGFwGIlKIGQD0NcNmioEDAc8YQPQ1w7ECJ2JV9DXDMwXeZ6BDXzOceHA4JA9wDvQV/Hv2NL2D6cdDldFPLZKud049Z8BNq9XUM+XsBQOIvmY4V+C5WBV9zXChwCUDHfqa4bmSehNT6tUuZ/8rdXsL1yJpqanMBgtl/QUDbprUDPt/WTjcd1r/gB58IyVuJktN9ZmcwFLJ4Nbe1aV9rxVgq5mslGOsODQH1CrcKHDD53bAWoV7DmGEfwALP8cbnQUAAA=="4BC8787D6B008C2C2603117B9D9250F0
 
BLUEPRINT:0,10,6001,0,0,0,0,0,638418676621490000,0.9.26.13026,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%2Fmin,%E8%93%9D%E7%9F%A9%E9%98%B5-60.000%20%2Fmin"H4sIAAAAAAAAC42TMU7DQBBFZ00cx7FjmxAnbSREQR1KpIyJxA04CKKAko5r+AyIA1BSQIEoabiJ2WXWnrV3kDzSKF/Wvj+z37GCfinbpBuANysVbPgUIvVQU90k19DYyvI8A4j106DzVn1w2H0ToyWTgI7VuNvdWejV0S9Xpr+jczi2hk1Cg2836k8ctRBPrR39dDBtDEyFuucNGTxPyGDSGny8p50B675Boju2BmVIBqHdrAJ43Pv64mD6MzrtwuTsAKYMAPqaYTPFwMqBIwYQfc3wVIBnzqroa4YjAY4ZqNHXDM88ONDJA1xqNR9z9zh+GPwLqRL6KZyki9Gppwy00wox9US4+4IBRF8znApw5qyKvmZ4IcA5AzX6muFMSL0MKfVizN3/S91+hVsnaVdTmQ2WwvpLBtpprmbYf2WB/t5p/RN68IOUuJnsaqqv6AxWQgb39mNf2XOVA1aSSSlco+TQWqAQ4bUAr/neLbAV4YZD6OBfpsdJm+YFAAA="53EE0214BB3E51FC00B6B86BF77F90A6
 
&nbsp;

     
                




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "122474363/DSQ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 晚上8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [122474363/DSQ] 自演化研究站无法配置加速配方 (Issue #22)





 
有图片吗

**Comment by wanghaowms** [comment]
<img width="1188" alt="图片11" src="https://github.com/122474363/DSQ/assets/37298585/58e28c33-2d8e-4e07-9645-3e0f439790f5">
<img width="465" alt="图片12" src="https://github.com/122474363/DSQ/assets/37298585/576e12a1-761e-4e2f-a443-a6ca8a40a724">
<img width="651" alt="图片13" src="https://github.com/122474363/DSQ/assets/37298585/ae3d3fe3-cebc-410d-8808-d2375cbfc23b">

**Comment by 122474363** [comment]
你是说这里面没有计算 加速吗。。这个要手动设置吧 我也不是太清楚，

**Comment by wanghaowms** [comment]
60蓝糖，生成图纸，增产剂使用加速。但是研究站使用自演化研究站，生成的蓝图却不是加速，而是额外产出。

**Comment by 122474363** [comment]
这个你可以尝试下手动调整，，蓝图这一块 我也不是太懂。。

**Comment by 122474363** [comment]
问题方向：https://github.com/122474363/DSQ/pull/24#issue-2114324894

**Comment by 122474363** [comment]
已修复：https://github.com/122474363/DSQ/commit/39a9f05a72a5adfad9cb181d9f954dc64393cb6b
