### ISSUE TITLE
为什么配送运输机不能生成蓝图（报错不是说制造台配方可以用吗

### ISSUE THREAD

**Issue by wistfate** [122474363/DSQ#9]
![VYM6( 29ZN_C5OVFA2%_SYJ](https://github.com/122474363/DSQ/assets/154920778/91588298-e191-4efa-b4af-02ab3ce3de19)

**Comment by 122474363** [comment]
[问题已解决](https://github.com/122474363/DSQ/commit/f545459ce712e0060cad1a087849b81c2439fcd5)

**Comment by god-singer** [comment]
这是因为运输机这个物品需要3进1出，但是蓝图生成只能在设备的一侧生成爪子，制造台的一侧只有3个位置，无法容纳4个爪子，所以无法生成蓝图
